In [2]:
import numpy as np
import pandas as pd

In [3]:
latlong=pd.read_csv('indian geography\district wise centroids.csv')

<>:1: SyntaxWarning: invalid escape sequence '\d'
<>:1: SyntaxWarning: invalid escape sequence '\d'
C:\Users\aashi\AppData\Local\Temp\ipykernel_2964\2421118002.py:1: SyntaxWarning: invalid escape sequence '\d'
  latlong=pd.read_csv('indian geography\district wise centroids.csv')

In [4]:
latlong.head()

                 State         District   Latitude  Longitude
0  Andaman and Nicobar  Andaman Islands  12.382571  92.822911
1  Andaman and Nicobar  Nicobar Islands   7.835291  93.511601
2       Andhra Pradesh         Adilabad  19.284514  78.813212
3       Andhra Pradesh        Anantapur  14.312066  77.460158
4       Andhra Pradesh         Chittoor  13.331093  78.927639

In [5]:
latlong.shape

(594, 4)

In [25]:
census=pd.read_csv('india census 2011\india-districts-census-2011.csv')

<>:1: SyntaxWarning: invalid escape sequence '\i'
<>:1: SyntaxWarning: invalid escape sequence '\i'
C:\Users\aashi\AppData\Local\Temp\ipykernel_2964\177401887.py:1: SyntaxWarning: invalid escape sequence '\i'
  census=pd.read_csv('india census 2011\india-districts-census-2011.csv')

In [7]:
census.head()

,District code,State name,District name,Population,Male,Female,Literate,Male_Literate,Female_Literate,SC,...,Power_Parity_Rs_90000_150000,Power_Parity_Rs_45000_150000,Power_Parity_Rs_150000_240000,Power_Parity_Rs_240000_330000,Power_Parity_Rs_150000_330000,Power_Parity_Rs_330000_425000,Power_Parity_Rs_425000_545000,Power_Parity_Rs_330000_545000,Power_Parity_Above_Rs_545000,Total_Power_Parity
0,1,JAMMU AND KASHMIR,Kupwara,870354,474190,396164,439654,282823,156831,1048,...,94,588,71,101,172,74,10,84,15,1119
1,2,JAMMU AND KASHMIR,Badgam,753745,398041,355704,335649,207741,127908,368,...,126,562,72,89,161,96,28,124,18,1066
2,3,JAMMU AND KASHMIR,Leh(Ladakh),133487,78971,54516,93770,62834,30936,488,...,46,122,15,22,37,20,14,34,17,242
3,4,JAMMU AND KASHMIR,Kargil,140802,77785,63017,86236,56301,29935,18,...,27,114,12,18,30,19,3,22,7,214
4,5,JAMMU AND KASHMIR,Punch,476835,251899,224936,261724,163333,98391,556,...,78,346,35,50,85,59,8,67,12,629

In [8]:
census.shape

(640, 118)

In [9]:
cols=['District code','District name','Population','Male','Female','Literate','Households_with_Internet','Housholds_with_Electric_Lighting']

In [10]:
census=census[cols]

In [11]:
final_df=latlong.merge(census,left_on='District',right_on='District name').drop(columns=['District name'])
final_df

,State,District,Latitude,Longitude,District code,Population,Male,Female,Literate,Households_with_Internet,Housholds_with_Electric_Lighting
0,Andhra Pradesh,Adilabad,19.284514,78.813212,532,2741239,1369597,1371642,1483347,5512,566108
1,Andhra Pradesh,Anantapur,14.312066,77.460158,553,4081148,2064495,2016653,2310960,8606,897970
2,Andhra Pradesh,Chittoor,13.331093,78.927639,554,4174064,2090204,2083860,2667878,13763,944555
3,Andhra Pradesh,East Godavari,16.782718,82.243207,545,5154296,2569688,2584608,3288577,22411,1297273
4,Andhra Pradesh,Guntur,15.884926,80.586576,548,4887813,2440521,2447292,2960441,19383,1186028
...,...,...,...,...,...,...,...,...,...,...,...
512,West Bengal,Maldah,25.080268,88.171917,332,3988845,2051541,1937304,2086432,5357,297716
513,West Bengal,Murshidabad,24.259507,88.168169,333,7103807,3627564,3476243,4055834,7951,541169
514,West Bengal,Nadia,23.564110,88.582930,336,5167600,2653768,2513832,3480555,12787,623729
515,West Bengal,Puruliya,23.254192,86.396853,340,2930115,1496996,1433119,1624905,3551,189889
516,West Bengal,Uttar Dinajpur,26.044619,88.235952,330,3007134,1551066,1456068,1489667,2883,199307

In [12]:
final_df['sex_ratio']=round((final_df['Female']/final_df['Male'])*100)

In [13]:
final_df['literacy_rate']=round((final_df['Literate']/final_df['Population'])*100)

In [14]:
final_df.head()

,State,District,Latitude,Longitude,District code,Population,Male,Female,Literate,Households_with_Internet,Housholds_with_Electric_Lighting,sex_ratio,literacy_rate
0,Andhra Pradesh,Adilabad,19.284514,78.813212,532,2741239,1369597,1371642,1483347,5512,566108,100.0,54.0
1,Andhra Pradesh,Anantapur,14.312066,77.460158,553,4081148,2064495,2016653,2310960,8606,897970,98.0,57.0
2,Andhra Pradesh,Chittoor,13.331093,78.927639,554,4174064,2090204,2083860,2667878,13763,944555,100.0,64.0
3,Andhra Pradesh,East Godavari,16.782718,82.243207,545,5154296,2569688,2584608,3288577,22411,1297273,101.0,64.0
4,Andhra Pradesh,Guntur,15.884926,80.586576,548,4887813,2440521,2447292,2960441,19383,1186028,100.0,61.0

In [15]:
final_df=final_df.drop(columns=['Male','Female','Literate'])

In [16]:
final_df.to_csv('india.csv',index=False)

In [19]:
list_of_state=list(final_df['State'].unique())

In [21]:
list_of_state.insert(0,'overall India')
list_of_state

['overall India',
 'Andhra Pradesh',
 'Arunachal Pradesh',
 'Assam',
 'Bihar',
 'Chandigarh',
 'Chhattisgarh',
 'Daman and Diu',
 'Goa',
 'Gujarat',
 'Haryana',
 'Himachal Pradesh',
 'Jammu and Kashmir',
 'Jharkhand',
 'Karnataka',
 'Kerala',
 'Madhya Pradesh',
 'Maharashtra',
 'Manipur',
 'Meghalaya',
 'Mizoram',
 'Nagaland',
 'Orissa',
 'Puducherry',
 'Punjab',
 'Rajasthan',
 'Sikkim',
 'Tamil Nadu',
 'Tripura',
 'Uttar Pradesh',
 'Uttaranchal',
 'West Bengal']

In [23]:
sorted(final_df.columns[5:])

['Households_with_Internet',
 'Housholds_with_Electric_Lighting',
 'Population',
 'literacy_rate',
 'sex_ratio']